ERAS = ["WoodenOx", "Spot", "Cheetah", "ANYmal"]

STATIC_METRICS = {
    "WoodenOx": {
        'mechanical_complexity': 30,
        'max_obstacle_height': 100,
        'max_slope_angle': 15,
        'speed': 0.3,
        'payload_ratio': 0.6,
        'autonomy_hours': 0,
        'weight_kg': 500,
        'payload_kg': 300,
        'terrain_types_supported': 3,
        'noise_level_db': 40,
        'cost_estimate_relative': 1,
        'control_method': '纯机械',
        'power_source': '人力',
        'sensing_capability': 1,
        'degrees_of_freedom': 1,
        'self_recovery': False,
        'historical_significance': 10,
        'innovation_index': 9,
    },
    "Spot": {
        'mechanical_complexity': 180,
        'max_obstacle_height': 300,
        'max_slope_angle': 35,
        'speed': 1.6,
        'payload_ratio': 0.47,
        'autonomy_hours': 1.5,
        'weight_kg': 32.5,
        'payload_kg': 14,
        'terrain_types_supported': 8,
        'noise_level_db': 60,
        'cost_estimate_relative': 1000,
        'control_method': 'AI+液压',
        'power_source': '电池+液压',
        'sensing_capability': 9,
        'degrees_of_freedom': 12,
        'self_recovery': True,
        'historical_significance': 7,
        'innovation_index': 9,
    },
    "Cheetah": {
        'mechanical_complexity': 220,
        'max_obstacle_height': 400,
        'max_slope_angle': 40,
        'speed': 6.4,
        'payload_ratio': 0.3,
        'autonomy_hours': 2.0,
        'weight_kg': 45,
        'payload_kg': 13.5,
        'terrain_types_supported': 5,
        'noise_level_db': 70,
        'cost_estimate_relative': 1500,
        'control_method': 'AI+电机',
        'power_source': '电池+电机',
        'sensing_capability': 8,
        'degrees_of_freedom': 12,
        'self_recovery': True,
        'historical_significance': 8,
        'innovation_index': 10,
    },
    "ANYmal": {
        'mechanical_complexity': 170,
        'max_obstacle_height': 200,
        'max_slope_angle': 25,
        'speed': 1.0,
        'payload_ratio': 0.2,
        'autonomy_hours': 4.0,
        'weight_kg': 50,
        'payload_kg': 10,
        'terrain_types_supported': 7,
        'noise_level_db': 55,
        'cost_estimate_relative': 1800,
        'control_method': 'AI+电机',
        'power_source': '电池+电机',
        'sensing_capability': 9,
        'degrees_of_freedom': 12,
        'self_recovery': True,
        'historical_significance': 7,
        'innovation_index': 8,
    },
}

STANDARD_SOURCES = {
    "Spot": {
        'model': "Boston Dynamics Spot Explorer",
        'source': "官网公开规格",
        'release_year': "2021发布",
    },
    "Cheetah": {
        'model': "MIT Biomimetic Robotics Lab Cheetah 3",
        'source': "论文公开数据",
        'release_year': "2018发布",
    },
    "ANYmal": {
        'model': "ANYbotics ANYmal D",
        'source': "官网公开规格",
        'release_year': "2020发布",
    },
    "WoodenOx": {
        'model': "诸葛亮木牛流马",
        'source': "历史记载",
        'release_year': "三国时期",
    },
}
